"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import environ
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

GEMINI_API_KEY = env('GEMINI_API_KEY')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'weather',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(default=f"postgresql://postgres:Admin@localhost:5432/weather_db")
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


WEATHER_CITIES = {
    "Cairo, Egypt": {"latitude": 30.0444, "longitude": 31.2357},
    "Alexandria, Egypt": {"latitude": 31.2001, "longitude": 29.9187},
    "Giza, Egypt": {"latitude": 30.0131, "longitude": 31.2089},
    "Zagazig, Egypt": {"latitude": 30.5877, "longitude": 31.5022},          # Sharqia
    "Mansoura, Egypt": {"latitude": 31.0409, "longitude": 31.3785},        # Dakahlia
    "Tanta, Egypt": {"latitude": 30.7865, "longitude": 31.0004},           # Gharbia
    "Damanhur, Egypt": {"latitude": 31.0341, "longitude": 30.4682},        # Beheira
    "Shibin El Kom, Egypt": {"latitude": 30.5539, "longitude": 31.0119},   # Monufia
    "Banha, Egypt": {"latitude": 30.4667, "longitude": 31.1833},           # Qalyubia
    "Kafr El Sheikh, Egypt": {"latitude": 31.1107, "longitude": 30.9388},  # Kafr El Sheikh
    "Damietta, Egypt": {"latitude": 31.4165, "longitude": 31.8133},        # Damietta
    "Port Said, Egypt": {"latitude": 31.2653, "longitude": 32.3019},       # Port Said
    "Ismailia, Egypt": {"latitude": 30.5965, "longitude": 32.2715},        # Ismailia
    "Suez, Egypt": {"latitude": 29.9668, "longitude": 32.5498},            # Suez
    "Marsa Matrouh, Egypt": {"latitude": 31.3543, "longitude": 27.2373},   # Matrouh
    "El Arish, Egypt": {"latitude": 31.1316, "longitude": 33.7984},        # North Sinai
    "El Tor, Egypt": {"latitude": 28.2400, "longitude": 33.6217},          # South Sinai
    "Beni Suef, Egypt": {"latitude": 29.0661, "longitude": 31.0994},       # Beni Suef
    "Faiyum, Egypt": {"latitude": 29.3084, "longitude": 30.8428},          # Faiyum
    "Minya, Egypt": {"latitude": 28.1099, "longitude": 30.7503},           # Minya
    "Asyut, Egypt": {"latitude": 27.1809, "longitude": 31.1837},           # Asyut
    "Sohag, Egypt": {"latitude": 26.5569, "longitude": 31.6948},           # Sohag
    "Qena, Egypt": {"latitude": 26.1551, "longitude": 32.7160},            # Qena
    "Luxor, Egypt": {"latitude": 25.6872, "longitude": 32.6396},           # Luxor
    "Aswan, Egypt": {"latitude": 24.0889, "longitude": 32.8998},           # Aswan
    "Hurghada, Egypt": {"latitude": 27.2579, "longitude": 33.8116},        # Red Sea
    "New Valley (Kharga), Egypt": {"latitude": 25.4514, "longitude": 30.5467},  # New Valley
}

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

from datetime import timedelta
CELERY_BEAT_SCHEDULE = {
    'fetch-weather-hourly': {
        'task': 'weather.tasks.fetch_weather_data',
        'schedule': timedelta(hours=1),
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/hour',
        'export': '3/hour',
    },

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Weather Tracker API',
    'DESCRIPTION': 'Weather data with JWT auth, favorites, and AI-generated summaries.',
    'VERSION': '1.0.0',
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'weather-tracker@example.com'