# Generated by Django 5.2.16 on 2026-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('api', 'API'), ('manual', 'Manual')], default='api', max_length=10)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
